### ISSUE TITLE
Front end cookie notify

### ISSUE THREAD

**Issue by kenlog** [novatio/silverstripe-gdpr-cookie-policy#1]
The notification does not appear "We use cookies on this website"

Tested on: 
silverstripe: 3.6.5@stable 
themes simple: 3.1.1

can you help me please? @gavro

**Comment by gavro** [comment]
Could you update the module to the last version and see if you're still having issues? If this did not help: Could you provide some more info (e.g. are you seeing errors when looking at your developer console what kind of JS libs are you using on your website, do you use requireJS, etc)?

Thnx!

**Comment by kenlog** [comment]
![cookienotify](https://user-images.githubusercontent.com/11728231/40228983-21072616-5a93-11e8-91c9-40fbcce06b3c.jpg)
Here's what the console tells me

The problem is encountered when jquery is loaded first
I tried to upload it after the script is notification works

**Comment by kenlog** [comment]
I suggest you add {$absoluteBaseURL} in CookiePolicyJSSnippet.ss in the case of sub-folders otherwise it will not work
